// Datos fijos de la app (textos de las pantallas y listas iniciales de jardinería y habitaciones).

export const PAGE_LABELS = {control:'Control','control-jardineria':'Control › Seguimiento Jardinería','control-habitaciones':'Control › Habitaciones con Plantas',
  home:'Inicio', operaciones:'Operaciones',
  checklist:'Operaciones › Checklist', stock:'Operaciones › Stock',
  inventario:'Operaciones › Inventario',
  'eventos-maison':'Operaciones › Eventos / Maison',
  'jardineria-ops':'Operaciones › Tareas Jardinería',
  'hab-ops':'Operaciones › Habitaciones con Plantas',
  'recepcion-pedidos':'Operaciones › Recepción de Pedidos',
  compras:'Compras', 'compras-floreria':'Compras › Florería',
  'compras-jardineria':'Compras › Jardinería',
  'compra-evento':'Compras › Compra por Evento',
  'stock-admin':'Compras › Gestión de Stock', floreros:'Compras › Stock de Floreros',
  comercial:'Área Comercial', 'eventos-comercial':'Comercial › Eventos',
  'historial-eventos':'Comercial › Historial de Eventos',
  'eventos-sin-floreria':'Comercial › Eventos sin Florería',
  cotizador:'Comercial › Cotizador',
  'cotizador-ops':'Cotizador',
  'ventas-externas':'Comercial › Ventas', caja:'Contable › Control de Caja',
  galeria:'Comercial › Galería de Trabajos',
  'lista-precios':'Comercial › Lista de Precios',
  'ramos-disponibles':'Comercial › Ramos Disponibles',
  'pedidos-ramos':'Comercial › Pedidos de Ramos',
  'pedidos-habitacion':'Comercial › Pedidos de Habitación',
  'home-hyatt':'Panel Hyatt',
  'cotizador-eventos-hyatt':'Cotizador de Eventos',
  'control-horarios':'Recursos Humanos › Horarios y Productividad',
  'recetas-arreglos':'Comercial › Composiciones',
  reportes:'Reportes', 'reportes-equipo':'Reportes › Equipo & Horarios',
  'reportes-ventas':'Reportes › Ventas & Comercial', 'reportes-hotel':'Reportes › Costo del Hotel',
  'crm-clientes':'CRM · Clientes',
  sucursales:'Administración de Sucursales',
  'dashboard-consolidado':'Dashboard Consolidado',
  'calendario': 'Calendario de Eventos',
  'proveedores': 'Proveedores',
  'rentabilidad-eventos': 'Contable › Rentabilidad',
  legajo: 'Recursos Humanos › Legajo de Empleados',
  evaluaciones: 'Recursos Humanos › Evaluaciones de Desempeño',
  liquidacion: 'Recursos Humanos › Liquidación Horas Extra',
  'precio-comparacion': 'Compras › Comparar Precios',
  'presupuestos': 'Comercial › Presupuestos Enviados',
  'cotizar-presupuesto': 'Comercial › Armar cotización',
  'costo-varas': 'Comercial › Costo de varas',
  'cierre-mensual': 'Contable › Cierre Mensual',
  'cierre-dia': 'Reportes › Cierre del Día',
  'tareas-gerencia': 'Gerencia › Tareas Pendientes'
};

export const JARDINERIA_BASE = [
  {section:"Palacio",group:"Entrada Alvear",task:"Rosales nunciature",last:"2026-05-19",visits:9},
  {section:"Palacio",group:"Entrada Alvear",task:"Rosales McGuire",last:"2026-05-19",visits:9},
  {section:"Palacio",group:"Entrada Alvear",task:"Buxus",last:"2026-05-19",visits:5},
  {section:"Palacio",group:"Entrada Alvear",task:"Magnolias",last:"2026-05-19",visits:5},
  {section:"Palacio",group:"Entrada Alvear",task:"Geranios Biblioteca",last:"2026-05-11",visits:2},
  {section:"Palacio",group:"Entrada Alvear",task:"Geranios Salón Privado",last:null,visits:0},
  {section:"Palacio",group:"Patio del Gimnasio",task:"Cantero de azaleas",last:"2026-05-15",visits:3},
  {section:"Palacio",group:"Patio del Gimnasio",task:"Cantero de monsteras",last:"2026-05-15",visits:3},
  {section:"Palacio",group:"Patio del Gimnasio",task:"Fuente",last:"2026-05-19",visits:4},
  {section:"Palacio",group:"Patio del Gimnasio",task:"Monsteras McGuire",last:"2026-05-15",visits:2},
  {section:"Palacio",group:"2do Piso",task:"Laureles de Jardín",last:"2026-05-18",visits:4},
  {section:"Palacio",group:"2do Piso",task:"Habitaciones",last:"2026-05-18",visits:5},
  {section:"Palacio",group:"2do Piso",task:"Orquídeas",last:"2026-05-18",visits:3},
  {section:"Palacio",group:"3ro y 4to Piso",task:"Jardineras con geranios",last:"2026-05-15",visits:5},
  {section:"Palacio",group:"3ro y 4to Piso",task:"Habitaciones",last:"2026-05-18",visits:7},
  {section:"Palacio",group:"3ro y 4to Piso",task:"Orquídeas",last:"2026-05-18",visits:4},
  {section:"Palacio",group:"3ro y 4to Piso",task:"Macetas con azareros (Azotea)",last:"2026-05-19",visits:2},
  {section:"Jardín Central",group:"Patio de la Florería",task:"Eugenias",last:"2026-05-19",visits:9},
  {section:"Jardín Central",group:"Patio de la Florería",task:"Kinotos",last:"2026-05-19",visits:9},
  {section:"Jardín Central",group:"Patio de la Florería",task:"Azareros",last:"2026-05-19",visits:9},
  {section:"Jardín Central",group:"Patio de la Florería",task:"Acer",last:"2026-05-19",visits:9},
  {section:"Jardín Central",group:"Patio de la Florería",task:"Monstera",last:"2026-05-16",visits:7},
  {section:"Jardín Central",group:"Terraza de Duhau",task:"Maceteros con Buxus",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Terraza de Piano Nobile",task:"Orquídeas Piano",last:"2026-05-19",visits:4},
  {section:"Jardín Central",group:"Terraza de Piano Nobile",task:"Cantero azalea Nunciatura",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Terraza de Piano Nobile",task:"Cantero azalea McGuire",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Terraza de Piano Nobile",task:"Macetitas de suculentas de mesas",last:"2026-05-19",visits:5},
  {section:"Jardín Central",group:"Cantero de Rosales Nunciatura",task:"Rosales Pierre de Rosan",last:"2026-05-19",visits:11},
  {section:"Jardín Central",group:"Cantero de Rosales Nunciatura",task:"Azarero",last:"2026-05-19",visits:10},
  {section:"Jardín Central",group:"Cantero de Rosales Nunciatura",task:"Helecho",last:"2026-05-19",visits:10},
  {section:"Jardín Central",group:"Cantero de Rosales Nunciatura",task:"Ericas",last:"2026-05-19",visits:10},
  {section:"Jardín Central",group:"Cantero de Rosales Nunciatura",task:"Cantero de geranios",last:"2026-05-19",visits:11},
  {section:"Jardín Central",group:"Cantero de azaleas McGuire",task:"Cantero de azaleas McGuire",last:"2026-05-05",visits:1},
  {section:"Jardín Central",group:"Cantero de azaleas McGuire",task:"Azaleas",last:"2026-05-19",visits:7},
  {section:"Jardín Central",group:"Césped Central",task:"Césped",last:"2026-05-19",visits:9},
  {section:"Jardín Central",group:"Césped Central",task:"Cycas",last:"2026-05-19",visits:8},
  {section:"Jardín Central",group:"Césped Central",task:"Rosales iceberg",last:"2026-05-19",visits:11},
  {section:"Jardín Central",group:"Césped Central",task:"Violetas rastreras",last:"2026-05-19",visits:9},
  {section:"Jardín Central",group:"Césped Central",task:"Azaleas",last:"2026-05-19",visits:8},
  {section:"Jardín Central",group:"Barra de Gioia",task:"Copones alegrías del hogar rojas",last:"2026-05-15",visits:7},
  {section:"Jardín Central",group:"Barra de Gioia",task:"Agaphantus enanos",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Barra de Gioia",task:"Canteros fijos de buxus Gioia",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Barra de Gioia",task:"Canteros móviles de buxus Gioia",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Cantero de Cipreses",task:"Neomaricas",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Cantero de Cipreses",task:"Magnolia",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Cantero Acer Palmatum",task:"Acer Palmatum",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Cantero Acer Palmatum",task:"Vincas",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Cantero Acer Palmatum",task:"Azaleas",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Terraza de la Tipa",task:"Tipa",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Terraza de la Tipa",task:"Cantero de ophiopogum",last:"2026-05-19",visits:7},
  {section:"Jardín Central",group:"Terraza de la Tipa",task:"Buxus",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Macetas (12) alegrías del hogar blancas",last:"2026-05-14",visits:3},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Acer Palmatum",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Azarero",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Ginkgos",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Azalea",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Aspidistras",last:"2026-05-19",visits:6},
  {section:"Jardín Central",group:"Bosquecito de Ginkgos",task:"Buxus (ventana lobby Posadas)",last:"2026-05-19",visits:6},
  {section:"Edificio Posadas",group:"Entrada Posadas",task:"Cantero de azaleas",last:"2026-05-19",visits:6},
  {section:"Edificio Posadas",group:"Entrada Posadas",task:"Macetas entrada de reja",last:"2026-05-19",visits:5},
  {section:"Edificio Posadas",group:"Entrada Posadas",task:"Cantero de helechos cyrtonium",last:"2026-05-19",visits:5},
  {section:"Edificio Posadas",group:"Pared de Helechos",task:"Helechos",last:"2026-05-18",visits:4},
  {section:"Edificio Posadas",group:"Pared de Helechos",task:"Cantero aspidistras",last:"2026-05-18",visits:4},
  {section:"Edificio Posadas",group:"Terraza de 5to Piso",task:"Palos borrachos",last:"2026-05-19",visits:2},
  {section:"Edificio Posadas",group:"Terraza de 5to Piso",task:"Cantero",last:"2026-05-19",visits:3},
  {section:"Edificio Posadas",group:"Huerta — Revisión General",task:"Estado sanitario de cada módulo",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Revisión General",task:"Uniformidad de crecimiento",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Revisión General",task:"Detección de estrés hídrico",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Control de Volumen",task:"Altura máxima 40–50 cm",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Control de Volumen",task:"Recorte selectivo",last:"2026-05-19",visits:10},
  {section:"Edificio Posadas",group:"Huerta — Control de Volumen",task:"Eliminación de material desprolijo",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Orden Visual",task:"Bordes limpios",last:"2026-05-19",visits:10},
  {section:"Edificio Posadas",group:"Huerta — Orden Visual",task:"Sin hojas secas visibles",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Orden Visual",task:"Sin tierra desbordada",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Orden Visual",task:"Sin herramientas olvidadas",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Orden Visual",task:"Superficie homogénea",last:"2026-05-19",visits:10},
  {section:"Edificio Posadas",group:"Huerta — Sistema de Riego",task:"Revisión visual de goteros",last:"2026-05-19",visits:10},
  {section:"Edificio Posadas",group:"Huerta — Sistema de Riego",task:"Verificación humedad sustrato",last:"2026-05-19",visits:11},
  {section:"Edificio Posadas",group:"Huerta — Sistema de Riego",task:"Ajuste estacional si corresponde",last:"2026-05-19",visits:9},
  {section:"Edificio Posadas",group:"Pisos 5to al 17",task:"Habitaciones",last:"2026-05-18",visits:7},
  {section:"Edificio Posadas",group:"Pisos 5to al 17",task:"Plantas de los pasillos",last:"2026-05-18",visits:6},
];

export const HABITACIONES_BASE = [
  {hab:"201",last:"2026-05-12",visits:14,notas:""},
  {hab:"202",last:"2026-05-04",visits:13,notas:""},
  {hab:"203",last:"2026-05-11",visits:6,notas:""},
  {hab:"204",last:"2026-05-06",visits:7,notas:""},
  {hab:"207",last:"2026-05-18",visits:5,notas:""},
  {hab:"208",last:"2026-05-18",visits:10,notas:""},
  {hab:"209",last:"2026-05-18",visits:9,notas:""},
  {hab:"302",last:"2026-05-11",visits:11,notas:""},
  {hab:"303",last:"2026-05-18",visits:11,notas:""},
  {hab:"304",last:"2026-05-07",visits:5,notas:""},
  {hab:"306",last:"2026-05-12",visits:12,notas:""},
  {hab:"307",last:"2026-05-12",visits:14,notas:""},
  {hab:"308",last:"2026-05-04",visits:7,notas:""},
  {hab:"309",last:"2026-05-12",visits:9,notas:""},
  {hab:"401",last:"2026-05-09",visits:10,notas:""},
  {hab:"402",last:"2026-05-09",visits:23,notas:""},
  {hab:"403",last:"2026-05-18",visits:10,notas:""},
  {hab:"404",last:"2026-05-12",visits:16,notas:""},
  {hab:"405",last:"2026-05-18",visits:8,notas:""},
  {hab:"504",last:"2026-05-18",visits:8,notas:""},
  {hab:"505",last:"2026-05-07",visits:8,notas:""},
  {hab:"506",last:"2026-05-18",visits:12,notas:""},
  {hab:"507",last:"2026-05-18",visits:8,notas:""},
  {hab:"508",last:"2026-05-06",visits:12,notas:""},
  {hab:"510",last:"2026-05-18",visits:12,notas:""},
  {hab:"511",last:"2026-05-18",visits:11,notas:""},
  {hab:"512",last:"2026-04-23",visits:8,notas:""},
  {hab:"1307",last:"2026-05-18",visits:9,notas:""},
  {hab:"1308",last:"2026-05-07",visits:16,notas:""},
  {hab:"1309",last:"2026-05-12",visits:16,notas:""},
  {hab:"1310",last:"2026-05-12",visits:9,notas:""},
  {hab:"1409",last:"2026-04-17",visits:9,notas:""},
];
